/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Scenes/Main.ls
 */
export class MainSceneBase extends Laya.Scene {
    public StartPanel!: Laya.Sprite;
}

